name: libtab
description: Flutter widgets for modelling tab notation, rendering charts of chord finger positions and tabs
version: 0.0.10
homepage: https://github.com/eighty4/libtab
repository: https://github.com/eighty4/libtab

environment:
  flutter: ">=3.7.0"
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: false
  generate: false
