name: libtab
description: Flutter widgets for rendering music charts
version: 0.0.2
homepage: https://github.com/eighty4/libtab
repository: https://github.com/eighty4/libtab

environment:
  flutter: ">=3.7.0"
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
