enum Chord {
  a,
  am,
  a7,
  amaj7,
  am7,
  b,
  bm,
  b7,
  bmaj7,
  bm7,
  c,
  cm,
  c7,
  cmaj7,
  cm7,
  d,
  dm,
  d7,
  dmaj7,
  dm7,
  e,
  em,
  e7,
  emaj7,
  em7,
  f,
  fm,
  f7,
  fmaj7,
  fm7,
  g,
  gm,
  g7,
  gmaj7,
  gm7,
  ;

  String label() => switch (this) {
        Chord.a => 'A',
        Chord.am => 'Am',
        Chord.a7 => 'A7',
        Chord.amaj7 => 'Amaj7',
        Chord.am7 => 'Am7',
        Chord.b => 'B',
        Chord.bm => 'Bm',
        Chord.b7 => 'B7',
        Chord.bmaj7 => 'Bmaj7',
        Chord.bm7 => 'Bm7',
        Chord.c => 'C',
        Chord.cm => 'Cm',
        Chord.c7 => 'C7',
        Chord.cmaj7 => 'Cmaj7',
        Chord.cm7 => 'Cm7',
        Chord.d => 'D',
        Chord.dm => 'Dm',
        Chord.d7 => 'D7',
        Chord.dmaj7 => 'Dmaj7',
        Chord.dm7 => 'Dm7',
        Chord.e => 'E',
        Chord.em => 'Em',
        Chord.e7 => 'E7',
        Chord.emaj7 => 'Emaj7',
        Chord.em7 => 'Em7',
        Chord.f => 'F',
        Chord.fm => 'Fm',
        Chord.f7 => 'F7',
        Chord.fmaj7 => 'Fmaj7',
        Chord.fm7 => 'Fm7',
        Chord.g => 'G',
        Chord.gm => 'Gm',
        Chord.g7 => 'G7',
        Chord.gmaj7 => 'Gmaj7',
        Chord.gm7 => 'Gm7',
      };
}
