enum Chord {
  a,
  am,
  a7,
  am7,
  b,
  bm,
  b7,
  c,
  cm,
  c7,
  d,
  dm,
  d7,
  dm7,
  e,
  em,
  e7,
  emaj7,
  f,
  fm,
  fmaj7,
  fm7,
  g,
  gm,
  g7,
  gsus4
}

extension ChordLabelFn on Chord {
  String id() => switch (this) {
        Chord.a => 'a',
        Chord.am => 'am',
        Chord.a7 => 'a7',
        Chord.am7 => 'am7',
        Chord.b => 'b',
        Chord.bm => 'bm',
        Chord.b7 => 'b7',
        Chord.c => 'c',
        Chord.cm => 'cm',
        Chord.c7 => 'c7',
        Chord.d => 'd',
        Chord.dm => 'dm',
        Chord.d7 => 'd7',
        Chord.dm7 => 'dm7',
        Chord.e => 'e',
        Chord.em => 'em',
        Chord.e7 => 'e7',
        Chord.emaj7 => 'emaj7',
        Chord.f => 'f',
        Chord.fm => 'fm',
        Chord.fmaj7 => 'fmaj7',
        Chord.fm7 => 'fm7',
        Chord.g => 'g',
        Chord.gm => 'gm',
        Chord.g7 => 'g7',
        Chord.gsus4 => 'gsus4'
      };
}
