name: Verify CI

on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/verify.yml
      - example/**
      - lib/**
      - test/**
      - analysis_options.yaml
      - pubspec.*
  pull_request:
    branches: [ main ]
  workflow_call:

env:
  flutter_version: 3.32.4

jobs:
  verified:
    runs-on: ubuntu-latest
    needs:
      - analyze
      - build-example
      - format
      - publish-dry-run
      - test
    steps:
      - run: echo "Green Acres is the place to be"

  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.flutter_version }}
          cache-sdk: true
      - name: analyze
        run: flutter analyze

  build-example:
    strategy:
      matrix:
        example:
          - single_measure_chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.flutter_version }}
          cache-sdk: true
      - name: build
        run: |
          flutter create .
          flutter pub get
          flutter build web
        working-directory: example/${{ matrix.example }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.flutter_version }}
          cache-sdk: true
      - name: format
        run: dart format example/lib lib test --set-exit-if-changed

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.flutter_version }}
          cache-sdk: true
      - name: test
        run: flutter test

  publish-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ env.flutter_version }}
          cache-sdk: true
      - name: publish dry run
        run: flutter packages pub publish --dry-run
