name: Tag a release
run-name: "Release: tag a `${{ inputs.semver_bump }}` release"

on:
  workflow_dispatch:
    inputs:
      semver_bump:
        type: choice
        options:
          - breaking
          - major
          - minor
          - patch
        default: patch

concurrency: release

jobs:

  verify:
    uses: ./.github/workflows/ci_verify.yml

  prepare:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      actions: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: ./.github/workflows/changelog_check.sh CHANGELOG.md
      - uses: dart-lang/setup-dart@v1
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm i -g @eighty4/changelog
      - name: bump semver ${{ inputs.semver_bump }}
        id: bump
        run: |
          changelog check
          dart pub bump ${{ inputs.semver_bump }}
          TAG="v$(grep "version: " pubspec.yaml | cut -d ' ' -f2)"
          git add CHANGELOG.md pubspec.yaml
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          git commit -m "publishing $TAG to pub.dev"
          git tag "$TAG"
          git push --atomic origin main "$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
      - name: gh workflow run release_publish.yml
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh workflow run release_publish.yml --ref ${{ steps.bump.outputs.tag }}
