name: Release (publish)
run-name: "Release: publish `${{ github.ref }}` to pub.dev"

on:
  workflow_dispatch:

concurrency: release

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: validate tag
        run: |
          [[ ! "${{ github.ref }}" =~ ^refs\/tags\/v\d{1,3}\.\d{1,3}\.\d{1,3}$ ]] && exit 1
      - uses: actions/checkout@v4
      - uses: flutter-actions/setup-flutter@v4
        with:
          cache-sdk: true
      - uses: flutter-actions/setup-pubdev-credentials@v1
      - name: flutter pub publish
        run: flutter pub publish -f

  create-gh-release:
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      contents: write
    steps:
      - run: |
          TAG=${GITHUB_REF##*/}
          VERSION=${TAG:1}
          RELEASE_NOTES=$(./.github/workflows/changelog_get.sh CHANGELOG.md $VERSION)
          PUB_URL="https://pub.dev/packages/libtab/versions/$VERSION"
          echo "[Published on pub.dev]($PUB_URL)\r\n\r\n### Release notes\r\n\r\n$RELEASE_NOTES" > release_notes.md
          gh release create "$TAG" --latest --notes-file release_notes.md --title "$TAG"
