name: Picking CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
        if: success() || failure()
      - run: dart format lib test --set-exit-if-changed
        if: success() || failure()
