name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  flutter-version: 3.10.5

jobs:
  verified:
    runs-on: ubuntu-22.04
    needs:
      - analyze
      - format
      - publish-dry-run
      - test
    steps:
      - run: echo "Green Acres is the place to be"

  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: analyze
        run: flutter analyze

  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: format
        run: dart format lib test --set-exit-if-changed

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        flutter-version: [ '3.10.5', '3.7.0' ]
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter-version }}
          channel: 'stable'
      - name: test
        run: flutter test

  publish-dry-run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter-version }}
          channel: 'stable'
      - name: publish dry run
        run: flutter packages pub publish --dry-run
